name: Azure App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Permitir execução do startup.sh
      run: chmod +x startup.sh

    - name: Zipar app
      run: zip -r app.zip . -x ".git/*" ".venv/*" "__pycache__/*"

    - name: Deploy para Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: AzureLAB001Ecommerce
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: app.zip
