name: Deploy para Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Remover ambiente virtual local (incompatível com Linux)
        run: rm -rf .venv

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Criar ambiente virtual
        run: python -m venv antenv

      - name: Ativar ambiente virtual e instalar dependências
        run: |
          source antenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Garantir permissão de execução do startup.sh
        run: chmod +x startup.sh

      - name: Criar .env com segredos
        run: |
          echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> .env
          echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> .env
          echo "SQL_USER=${{ secrets.SQL_USER }}" >> .env
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> .env
          echo "BLOB_CONNECTION_STRING=${{ secrets.BLOB_CONNECTION_STRING }}" >> .env
          echo "BLOB_CONTAINER_NAME=${{ secrets.BLOB_CONTAINER_NAME }}" >> .env
          echo "BLOB_ACCOUNT_NAME=${{ secrets.BLOB_ACCOUNT_NAME }}" >> .env

      - name: Publicar código no Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: AzureLAB001Ecommerce
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
